import { FactMood } from '@/types/mood';

export interface Topic {
  slug: string;
  title: string;
  description: string;
  emoji: string;
  mood: FactMood;
}

export const topics: Topic[] = [
  {
    slug: 'braincells',
    title: 'Brain Facts',
    description: 'Fun facts about brain cells, neurons, and how your brain works.',
    emoji: '🧠',
    mood: 'general',
  },
  {
    slug: 'coffee',
    title: 'Coffee Facts',
    description: 'Fascinating facts about coffee, caffeine, brewing methods, and coffee culture around the world.',
    emoji: '☕',
    mood: 'general',
  },
  {
    slug: 'greek-mythology',
    title: 'Greek Mythology Facts',
    description: 'Fascinating facts about Greek gods, heroes, monsters, and the epic stories that shaped Western culture.',
    emoji: '⚡',
    mood: 'niche',
  },
  {
    slug: 'space',
    title: 'Space Facts',
    description: 'Fascinating facts about space, planets, stars, black holes, astronauts, and the universe beyond Earth.',
    emoji: '🚀',
    mood: 'general',
  },
  {
    slug: 'electricity',
    title: 'Electricity Facts',
    description: 'Shocking facts about electricity, lightning, energy, and how electrical power works.',
    emoji: '⚡',
    mood: 'general',
  },
  {
    slug: 'mining',
    title: 'Mining Facts',
    description: 'Dig deep into fascinating facts about mining, minerals, geology, and the history of extracting resources from the Earth.',
    emoji: '⛏️',
    mood: 'niche',
  },
  {
    slug: 'engines',
    title: 'Engines Facts',
    description: 'Rev up your knowledge with fascinating facts about engines, how they work, automotive history, and engine technology.',
    emoji: '🔧',
    mood: 'niche',
  },
  {
    slug: 'supercars',
    title: 'Supercars Facts',
    description: 'Speed into fascinating facts about supercars, hypercars, legendary brands, and the world\'s most extreme automobiles.',
    emoji: '🏎️',
    mood: 'niche',
  },
  {
    slug: 'movie-quotes',
    title: 'Movie Quotes Facts',
    description: 'Discover fascinating facts about famous movie quotes, their origins, misquotes, cultural impact, and the stories behind iconic lines.',
    emoji: '🎬',
    mood: 'obscure',
  },
  {
    slug: 'beer',
    title: 'Beer Facts',
    description: 'Fascinating facts about beer, brewing, history, culture, styles, and everything you need to know about the world\'s oldest alcoholic beverage.',
    emoji: '🍺',
    mood: 'niche',
  },
  {
    slug: 'whiskey',
    title: 'Whiskey Facts',
    description: 'Fascinating facts about whiskey styles, grains, aging, barrels, regions, and the craft behind great pours.',
    emoji: '🥃',
    mood: 'niche',
  },
  {
    slug: 'cocktails',
    title: 'Cocktails Facts',
    description: 'Fascinating facts about cocktails, their history, recipes, famous drinks, bartending techniques, and the stories behind iconic mixed drinks.',
    emoji: '🍸',
    mood: 'niche',
  },
  {
    slug: 'presidents',
    title: 'Presidents Facts',
    description: 'Fascinating facts about U.S. presidents, their powers, history, and the presidency.',
    emoji: '🇺🇸',
    mood: 'general',
  },
  {
    slug: 'cars',
    title: 'Cars Facts',
    description: 'Fascinating facts about cars, automotive history, manufacturing, and how automobiles work.',
    emoji: '🚗',
    mood: 'general',
  },
  {
    slug: 'bible',
    title: 'The Bible Facts',
    description: 'Fascinating facts about the Bible, its structure, history, translations, and literary content.',
    emoji: '📖',
    mood: 'general',
  },
  {
    slug: 'organs',
    title: 'Organs Facts',
    description: 'Fascinating facts about human body organs, their functions, anatomy, and how they work together.',
    emoji: '🫀',
    mood: 'general',
  },
  {
    slug: 'planes',
    title: 'Planes Facts',
    description: 'Fascinating facts about airplanes, aviation history, flight technology, and how planes work.',
    emoji: '✈️',
    mood: 'general',
  },
  {
    slug: 'world-leaders',
    title: 'World Leaders Facts',
    description: 'Fascinating facts about world leaders, historical figures, and influential political leaders throughout history.',
    emoji: '👑',
    mood: 'general',
  },
  {
    slug: 'elements',
    title: 'Elements Facts',
    description: 'Fascinating facts about chemical elements, the periodic table, and the building blocks of matter.',
    emoji: '⚛️',
    mood: 'general',
  },
  {
    slug: 'philosophy',
    title: 'Philosophy Facts',
    description: 'Fascinating facts about philosophy, famous philosophers, and the great ideas that have shaped human thought.',
    emoji: '🤔',
    mood: 'general',
  },
  {
    slug: 'seinfeld',
    title: 'Seinfeld Facts',
    description: 'Fascinating facts about Seinfeld, the iconic sitcom, its characters, episodes, and behind-the-scenes stories.',
    emoji: '📺',
    mood: 'obscure',
  },
  {
    slug: 'olympics',
    title: 'Olympics Facts',
    description: 'Fascinating facts about the Olympic Games, its history, athletes, records, and the world\'s greatest sporting event.',
    emoji: '🏅',
    mood: 'general',
  },
  {
    slug: 'internet',
    title: 'The Internet Facts',
    description: 'Fascinating facts about the internet, its history, development, and how it has transformed the world.',
    emoji: '🌐',
    mood: 'general',
  },
  {
    slug: 'octopi',
    title: 'Octopus Facts',
    description: 'Fascinating facts about octopuses, their intelligence, anatomy, behavior, and incredible abilities.',
    emoji: '🐙',
    mood: 'general',
  },
  {
    slug: 'snakes',
    title: 'Snakes Facts',
    description: 'Fascinating facts about snakes, their anatomy, behavior, venom, and incredible adaptations.',
    emoji: '🐍',
    mood: 'general',
  },
  {
    slug: 'sharks',
    title: 'Sharks Facts',
    description: 'Fascinating facts about sharks, their anatomy, behavior, and incredible adaptations.',
    emoji: '🦈',
    mood: 'general',
  },
  {
    slug: 'oceans',
    title: 'Oceans Facts',
    description: 'Fascinating facts about the world\'s oceans, their depths, currents, and importance to life on Earth.',
    emoji: '🌊',
    mood: 'general',
  },
  {
    slug: 'mountains',
    title: 'Mountains Facts',
    description: 'Fascinating facts about mountains, their formation, height records, and impact on climate and ecosystems.',
    emoji: '⛰️',
    mood: 'general',
  },
  {
    slug: 'ancient-egypt',
    title: 'Ancient Egypt Facts',
    description: 'Fascinating facts about ancient Egypt, pharaohs, pyramids, hieroglyphs, and one of history\'s greatest civilizations.',
    emoji: '🏺',
    mood: 'general',
  },
  {
    slug: 'chocolate',
    title: 'Chocolate Facts',
    description: 'Fascinating facts about chocolate, its history, production, health benefits, and cultural significance.',
    emoji: '🍫',
    mood: 'general',
  },
  {
    slug: 'spices',
    title: 'Spices Facts',
    description: 'Fascinating facts about spices, the spice trade, their history, and how they shaped world exploration.',
    emoji: '🌶️',
    mood: 'general',
  },
  {
    slug: 'art',
    title: 'Art Facts',
    description: 'Fascinating facts about art, famous artists, art movements, techniques, and masterpieces throughout history.',
    emoji: '🎨',
    mood: 'general',
  },
  {
    slug: 'operating-theatre',
    title: 'The Operating Theatre Facts',
    description: 'Fascinating facts about operating rooms, surgery, medical procedures, and the history of surgical medicine.',
    emoji: '🏥',
    mood: 'niche',
  },
  {
    slug: 'ethiopian-tribes',
    title: 'Ethiopian Tribes Facts',
    description: 'Fascinating facts about Ethiopian tribes, their diverse cultures, traditions, languages, and unique ways of life.',
    emoji: '🏛️',
    mood: 'obscure',
  },
  {
    slug: 'denominations',
    title: 'Denominations Facts',
    description: 'Fascinating facts about religious denominations, their history, differences, beliefs, and how they developed over time.',
    emoji: '⛪',
    mood: 'general',
  },
  {
    slug: 'number-one-singles',
    title: 'Number One Singles Facts',
    description: 'Fascinating facts about number one singles, chart-topping hits, music records, and the artists who dominated the charts.',
    emoji: '🎵',
    mood: 'general',
  },
  {
    slug: 'ai',
    title: 'A.I Facts',
    description: 'Fascinating facts about artificial intelligence, machine learning, AI history, and how AI is transforming the world.',
    emoji: '🤖',
    mood: 'general',
  },
  {
    slug: 'robots',
    title: 'Robots Facts',
    description: 'Fascinating facts about robots, from industrial automation to humanoid robots, robotic surgery, and the future of robotics.',
    emoji: '🤖',
    mood: 'niche',
  },
  {
    slug: 'drones',
    title: 'Drones Facts',
    description: 'Fascinating facts about drones, UAVs, their applications in delivery, agriculture, cinematography, and military use.',
    emoji: '🚁',
    mood: 'niche',
  },
  {
    slug: 'explorers',
    title: 'Explorers Facts',
    description: 'Fascinating facts about famous explorers, their journeys, discoveries, and the adventures that shaped our world.',
    emoji: '🗺️',
    mood: 'general',
  },
  {
    slug: 'simpsons',
    title: 'The Simpsons Facts',
    description: 'Fascinating facts about The Simpsons, its characters, episodes, catchphrases, cultural impact, and behind-the-scenes stories from the longest-running animated series.',
    emoji: '🍩',
    mood: 'obscure',
  },
  {
    slug: 'memes',
    title: 'Memes Facts',
    description: 'Fascinating facts about internet memes, their origins, evolution, cultural impact, and how they\'ve shaped digital culture and communication.',
    emoji: '😂',
    mood: 'obscure',
  },
  {
    slug: 'bamboo',
    title: 'Bamboo Facts',
    description: 'Fascinating facts about bamboo, its incredible uses, weird properties, strength, growth speed, and how this versatile grass is used in everything from construction to technology.',
    emoji: '🎋',
    mood: 'niche',
  },
  {
    slug: 'technology-timeline',
    title: 'Technology Timeline Facts',
    description: 'Fascinating facts tracing the evolution of technology from punch cards and typewriters through to smartphones, mapping the incredible journey of computing and digital innovation.',
    emoji: '📱',
    mood: 'general',
  },
  {
    slug: 'latitude-longitude',
    title: 'Latitude and Longitude Facts',
    description: 'Fascinating facts about latitude and longitude, how coordinate systems work, the history of navigation, GPS technology, and how these two numbers can pinpoint any location on Earth.',
    emoji: '🌍',
    mood: 'niche',
  },
  {
    slug: 'greenland',
    title: 'Greenland Facts',
    description: 'Fascinating facts about Greenland, the world\'s largest island, its massive ice sheet, unique culture, extreme climate, and the challenges and wonders of living in the Arctic.',
    emoji: '🧊',
    mood: 'niche',
  },
  {
    slug: 'austronesian-migration',
    title: 'Austronesian Migration Facts',
    description: 'Fascinating facts about the Austronesian migration, one of the most extensive human migrations in history, spreading across the Pacific and Indian Oceans from Taiwan to Madagascar, Easter Island, and New Zealand.',
    emoji: '🛶',
    mood: 'niche',
  },
  {
    slug: 'dutch-empire',
    title: 'Dutch Empire Facts',
    description: 'Fascinating facts about the Dutch Empire, one of the largest colonial empires in history, spanning from the 17th to 20th century, with the Dutch East India Company, global trade dominance, and colonies across five continents.',
    emoji: '🇳🇱',
    mood: 'general',
  },
  {
    slug: 'obscure-fast-food',
    title: 'Obscure Fast Food Facts',
    description: 'Fascinating facts about obscure fast food chains, regional favorites, secret menus, discontinued items, unusual menu creations, and the hidden world of fast food beyond the major chains.',
    emoji: '🍔',
    mood: 'obscure',
  },
];

